### ISSUE TITLE
Departures gives JSON error

### ISSUE THREAD

**Issue by hashworks** [juliuste/lvb#24]
```node
import { departures } from "lvb"
const d = await departures("12714", Date.now())
```

Station is `Hermann-Liebmann-Str./Eisenbahnstr.`

```
FetchError: invalid json response body at https://www.l.de/verkehrsbetriebe/fahrplan/ reason: Unexpected token < in JSON at position 0
    at /path/node_modules/node-fetch/lib/index.js:272:32
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at path/file.ts:38:19 {
  type: 'invalid-json'
```

Maybe they changed the API.

**Comment by maweki** [comment]
I think the endpoint changed. The webinterface is querying `https://www.l.de/verkehrsbetriebe/fahrplan?ws_info_stop` while this lib is querying `https://www.l.de/verkehrsbetriebe/fahrplan` which is a redirect to the html which is exactly the error.

Adding the query string should fix it.

**Comment by hashworks** [comment]
I don't think so. I asked chromium to give me the cURL command for the API request and removed everything but the raw POST data, including the GET parameters you mentioned – which works:
```
curl 'https://www.l.de/verkehrsbetriebe/fahrplan' --data-raw 'results%5B5%5D%5B3%5D%5Bfunction%5D=ws_info_stop&results%5B5%5D%5B3%5D%5Bdata%5D=%5B%7B%22name%22%3A%22results%5B5%5D%5B3%5D%5Bstop%5D%22%2C%22value%22%3A%22Leipzig%2C+Hermann-Liebmann-Str.%2F+Eisenbahnstr.%22%7D%2C%7B%22name%22%3A%22results%5B5%5D%5B3%5D%5Bdate%5D%22%2C%22value%22%3A%2205.06.2020%22%7D%2C%7B%22name%22%3A%22results%5B5%5D%5B3%5D%5Btime%5D%22%2C%22value%22%3A%22%22%7D%2C%7B%22name%22%3A%22results%5B5%5D%5B3%5D%5Bmode%5D%22%2C%22value%22%3A%22stop%22%7D%5D' | jq
```
https://fb.kromlinger.eu/acTpkS/json

I'll take a look at the POST data.

Oh, and nice to "see" you again Mario ;)


EDIT: Data without URL encoding
```
results[5][3][function]: ws_info_stop
results[5][3][data]: [{"name":"results[5][3][stop]","value":"Leipzig, Hermann-Liebmann-Str./ Eisenbahnstr."},{"name":"results[5][3][date]","value":"05.06.2020"},{"name":"results[5][3][time]","value":"15:00"},{"name":"results[5][3][mode]","value":"stop"}]
```

**Comment by hashworks** [comment]
Using `results[5][3]` instead of `results[5][2]` passes the tests.
